#!/usr/bin/env node
/**
 * Gzips tools/web_ui/index.html and emits firmware/src/web_ui.h as a
 * PROGMEM byte array, served by web_server.cpp with Content-Encoding: gzip.
 * No SPIFFS/LittleFS — the page ships inside the firmware binary, so a
 * single `pio run -t upload` is still the whole deploy story.
 *
 * Usage: node build_web_ui.js [--in FILE] [--out FILE]
 */

const fs = require('fs');
const path = require('path');
const zlib = require('zlib');

const args = process.argv.slice(2);
const opt = (k, def) => { const i = args.indexOf(k); return i >= 0 ? args[i + 1] : def; };

const IN_FILE = path.resolve(opt('--in', path.join(__dirname, 'web_ui', 'index.html')));
const OUT_FILE = path.resolve(opt('--out',
  path.join(__dirname, '..', 'firmware', 'src', 'web_ui.h')));

function main() {
  if (!fs.existsSync(IN_FILE)) {
    console.error(`No source page at ${IN_FILE}`);
    process.exit(1);
  }

  const html = fs.readFileSync(IN_FILE);
  const gz = zlib.gzipSync(html, { level: 9 });

  let out = '';
  out += '// ============================================================\n';
  out += '// Web dashboard/config page — generated by tools/build_web_ui.js\n';
  out += '// from tools/web_ui/index.html. Do not edit by hand — edit the\n';
  out += '// source page and re-run the generator.\n';
  out += '// ============================================================\n';
  out += '#pragma once\n#include <stdint.h>\n\n';
  out += `static const uint8_t INDEX_HTML_GZ[] = {\n`;
  for (let i = 0; i < gz.length; i += 20) {
    out += '    ' + Array.from(gz.slice(i, i + 20)).map(b => '0x' + b.toString(16).padStart(2, '0')).join(',') + ',\n';
  }
  out += '};\n';
  out += `static const size_t INDEX_HTML_GZ_LEN = ${gz.length};\n`;

  fs.writeFileSync(OUT_FILE, out);
  console.log(`Wrote ${OUT_FILE} (${html.length} bytes -> ${gz.length} gzipped, ${(out.length / 1024).toFixed(1)} KB header)`);
}

main();
